/*
 * Revcord, a Discord client mod
 * Copyright (c) 2026 Vendicated and contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

import { mkdir, writeFile } from "fs/promises";
import { join } from "path";

export interface ScaffoldOptions {
    /** Plugin id, e.g. "my-cool-plugin" */
    id: string;
    /** Human readable name */
    name?: string;
    /** Short description */
    description?: string;
    /** Author display name */
    author?: string;
    /** Author snowflake id (string/number) */
    authorId?: string | number;
    /** Where to write the plugin (default: src/plugins/<id>) */
    outDir?: string;
    /** Include example command / patch / stylesheet */
    examples?: boolean;
}

function toPascal(id: string): string {
    return id.split(/[-_]/).map(s => s.charAt(0).toUpperCase() + s.slice(1)).join("");
}

function pluginSource(opts: ScaffoldOptions): string {
    const name = opts.name ?? toPascal(opts.id);
    const description = opts.description ?? "A Revcord plugin";
    const author = opts.author ?? "You";
    const authorId = opts.authorId ?? "0";

    const examples = opts.examples !== false;

    return `/*
 * Revcord plugin: ${name}
 * Generated by the Revcord Plugin SDK
 */

import { plugin, OptionType } from "@api/PluginSDK";

export default plugin("${name}", ${JSON.stringify(description)})
    .by(${JSON.stringify(author)}, ${JSON.stringify(String(authorId))})
${examples ? `    .command({
        name: "hello-${opts.id}",
        description: "Says hello from ${name}",
        run: () => { alert("Hello from ${name}!"); return "said hi"; }
    })
    .stylesheet(\`
        /* Your plugin styles go here */
        [class*="app"] { /* outline: 2px solid rebeccapurple; */ }
    \`)
    .setting("enabled", {
        type: OptionType.BOOLEAN,
        description: "Master switch for ${name}",
        default: true
    })
    .start(() => { console.log("[${name}] started"); })
` : `    .start(() => { console.log("[${name}] started"); })
`}
    .build();
`;
}

/**
 * Scaffold a new Revcord plugin on disk.
 *
 * Creates `src/plugins/<id>/index.ts` (plus a README) with a working plugin
 * built via the Supreme Plugin SDK. This is the fastest way to start a plugin.
 *
 * @returns the absolute path of the created index.ts
 */
export async function scaffoldPlugin(opts: ScaffoldOptions): Promise<string> {
    const base = opts.outDir ?? join(process.cwd(), "src", "plugins", opts.id);
    await mkdir(base, { recursive: true });

    const indexPath = join(base, "index.ts");
    await writeFile(indexPath, pluginSource(opts), "utf-8");

    await writeFile(join(base, "README.md"), `# ${opts.name ?? toPascal(opts.id)}\n\n${opts.description ?? "A Revcord plugin"}\n`, "utf-8");

    return indexPath;
}
